global:
  scrape_interval:     5s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'static'
    scrape_interval: 5s
    static_configs:
      - targets: ['localhost:9090', 'autoscaling-demo:8888']
